[package]
name = "website_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
rand = "0.8"
fake-useragent = "0.1.2"
scraper = "0.12"
url = "2.2"
[lib]
crate-type = ["cdylib"]